services:
  - type: web
    name: flowtv-app
    env: node
    plan: starter
    buildCommand: rm -rf dist node_modules/.vite && npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
