services:
  - type: web
    name: flowtv-app
    env: node
    plan: starter
    buildCommand: rm -rf dist node_modules/.vite && npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: VITE_SUPABASE_URL
        value: https://kvyloomugemyyokkervq.supabase.co
      - key: VITE_SUPABASE_PUBLISHABLE_KEY
        value: sb_publishable_5gEE3MzDtpkqUJb6ENfqzg_yEKKvIu2
      - key: SUPABASE_URL
        value: https://kvyloomugemyyokkervq.supabase.co
      - key: SUPABASE_PUBLISHABLE_KEY
        value: sb_publishable_5gEE3MzDtpkqUJb6ENfqzg_yEKKvIu2
